[package]
name = "actix_mongo"
version = "0.1.0"
authors = ["Carmen DeCastro <43592660+twoofswords@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
